/*
Create table fact_player_day
 */
CREATE OR REPLACE TABLE
fantasy_premier_league.fact_player_day
(
    player_sk STRING NOT NULL,
    player_id STRING NOT NULL,
    team_sk STRING NOT NULL,
    team_id STRING NOT NULL,
    position_id STRING NOT NULL,
    ict_index_rank INT,
    threat_rank INT,
    influence_rank_type INT,
    ict_index_rank_type INT,
    threat FLOAT64,
    bps INT,
    cost_change_event_fall INT,
    penalties_saved INT,
    status STRING,
    own_goals INT,
    goals_scored INT,
    cost_change_event INT,
    minutes INT,
    influence_rank INT,
    value_form FLOAT64,
    transfers_out_event INT,
    yellow_cards INT,
    transfers_out INT,
    penalties_order INT,
    transfers_in_event INT,
    event_points INT,
    assists INT,
    total_points INT,
    saves INT,
    creativity_rank INT,
    threat_rank_type INT,
    points_per_game FLOAT64,
    now_cost INT,
    in_dreamteam BOOL,
    red_cards INT,
    goals_conceded INT,
    news STRING,
    news_added TIMESTAMP,
    bonus INT,
    form FLOAT64,
    creativity FLOAT64,
    cost_change_start_fall INT,
    ict_index FLOAT64,
    chance_of_playing_this_round INT,
    creativity_rank_type INT,
    cost_change_start INT,
    direct_freekicks_order INT,
    dreamteam_count INT,
    chance_of_playing_next_round INT,
    selected_by_percent FLOAT64,
    transfers_in INT,
    clean_sheets INT,
    ep_next FLOAT64,
    value_season FLOAT64,
    corners_and_indirect_freekicks_order INT,
    influence FLOAT64,
    penalties_missed INT,
    ep_this FLOAT64,
    source_date DATE NOT NULL
)
PARTITION BY source_date
OPTIONS(description="Player day fact table")